### ISSUE TITLE
Section 1.3.1 Incorrect formula of circle area

### ISSUE THREAD

**Issue by jarmol** [moocfi/haskell-mooc#105]
Haskell MOOC Part 1
Section 1.3.1 Features

Algebraic datatypes / Pattern matching

This is the formula of circle's circumference:
area (Circle radius) = 2 * pi * radius

The correct formula of the circle area is here:
area (Circle radius) = pi * radius * radius

That is equivalent to this:
area (Circle radius) = pi * radius^2

**Comment by opqdonut** [comment]
thanks :sweat_smile:
