### ISSUE TITLE
Set2a Ex2: test for "takeFinal" is incomplete

### ISSUE THREAD

**Issue by muzimuzhi** [moocfi/haskell-mooc#18]
Both the test and module solution for Set2a, Ex2 `takeFinal` don't take the case mentioned in exercise instructions

> If the list is shorter than n, return all elements.

into consideration

Exercise instructions:
https://github.com/moocfi/haskell-mooc/blob/62654872313af9e6e5fcd6346f1064cecbac77a6/exercises/Set2a.hs#L27-L35

Tests (here k is always smaller than the length of list):
https://github.com/moocfi/haskell-mooc/blob/62654872313af9e6e5fcd6346f1064cecbac77a6/exercises/Set2aTest.hs#L42-L51

And the corresponding module solution (https://haskell.mooc.fi/model/Set2a.hs):
```haskell
takeFinal :: Int -> [a] -> [a]
takeFinal n xs = drop (length xs - n) xs
```

**Comment by opqdonut** [comment]
Great that you noticed this! Fixed now
