### ISSUE TITLE
Use links to latest hackage doc pages

### ISSUE THREAD

**Issue by muzimuzhi** [moocfi/haskell-mooc#19]
Unless the material need to stick to specific version of GHC/haskell package, I think it's preferable to use general links which will redirect to latest version of hackage doc pages.

For example, [current link](https://github.com/moocfi/haskell-mooc/blob/62654872313af9e6e5fcd6346f1064cecbac77a6/part1.html#L2024)
```html
<a href="http://hackage.haskell.org/package/base-4.12.0.0/docs/src/GHC.Base.html#map">Here’s map</a>
```
suggested link (https used)
```html
<a href="https://hackage.haskell.org/package/base/docs/src/GHC.Base.html#map">Here’s map</a>
```
which will redirect to doc page for the latest `base-4.14.1.0`.

6 such links are found in `part1.html`:

```
$ grep -rno 'https\?://hackage\.haskell\.org/package/[a-xA-Z]\+-.*\.html' part1.html

part1.html:2024:http://hackage.haskell.org/package/base-4.12.0.0/docs/src/GHC.Base.html
part1.html:2028:http://hackage.haskell.org/package/base-4.12.0.0/docs/src/GHC.List.html
part1.html:2605:https://hackage.haskell.org/package/containers-0.6.0.1/docs/Data-Map-Lazy.html
part1.html:3273:https://hackage.haskell.org/package/base-4.12.0.0/docs/Prelude.html
part1.html:3293:https://hackage.haskell.org/package/base-4.12.0.0/docs/Prelude.html
part1.html:3548:https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-List-NonEmpty.html
```

**Comment by opqdonut** [comment]
Hi and thanks for the report! I'm intentionally trying to link to the versions of packages that the tests use. This (currently) means [the Stack lts-14.9 snapshot](https://www.stackage.org/lts-14.9).

**Comment by muzimuzhi** [comment]
got it. Many Thanks for the nice course, and look forward to the part 2.
