### ISSUE TITLE
Lecture 10 Quiz

### ISSUE THREAD

**Issue by seaerchin** [moocfi/haskell-mooc#22]
### What's wrong 
In lecture 10, the question 

```
Which of these values is not in weak head normal form?

1. map
2. f 1 : map f (2 : [])
3. Just (not False)
4. (\x -> x) True
```
does not have an answer attached to it (unable to click) 

### Suggested Fix
Add a ```:active``` css class onto the ```<li>``` elements

**Comment by opqdonut** [comment]
thanks for spotting that!

**Comment by seaerchin** [comment]
My pleasure! also have a follow up question, the materials for part 10 state that ```An expression is in WHNF if it can’t be evaluated on its top level.``` but then proceeds to give the examples of a constant. Why can't constants be evaluated?
