### ISSUE TITLE
Exercise Set 8, question 3 ( implement a rectangle) - the given coordinate is the bottom-left one, not upper-left

### ISSUE THREAD

**Issue by timmyjose** [moocfi/haskell-mooc#28]
As the title says. The question would make sense if it were the traditional graphics coordinate system (where the top-left of the screen is (0, 0) and the axes increase top-down and left-right), but since that is not mentioned, in the normal Euclidean coordinate system, the test passes if we consider the given coordinate for the rectangle as the bottom-left, and not the upper-left. 

Also, the coordinates appear to be inclusive for the starting corner, but exclusive for the opposite corner.

Am I missing something, or is this really a typo?

**Comment by muzimuzhi** [comment]
I think the test has adapted, see https://github.com/moocfi/haskell-mooc/commit/5bb429484e66649dc2ec0cac65f6c59b166e95c6.

**Comment by timmyjose** [comment]
@muzimuzhi Thank you for linking that commit - it helps understand the situation better.

Another interesting bit is that the test file has this line of code for the given exercise (which I had wrongly marked as exercise 4 instead of exercise 3,  fixed now!) - `  conjoin [checkShape x y True rect | x <- [x0..x0+w-1], y <- [y0..y0+h-1]]`

So it it does take values in the range `[x0, x0+w)` and `[y0, y0+h)`.  So my assumption was right, and as per your commit link, they did have the intention of modifying the expectation to be that of a rectangle whose upper-left coordinates are given, but in the "screen coordinate system". 

I think the text of the question should be updated to make it consistent - either mention that this is the "screen coordinate/graphics coordinate system" with the given coordinates as the upper-left corer of the rectangle, or that the given coordinates are for the bottom-left (assuming the normal Euclidean coordinate system).

**Comment by opqdonut** [comment]
I tried to add a clarification about the coordinate system earlier in commit b88f7882c91793f9a3f7c71d462b006319f8ad4d – perhaps you're working on an older version of the exercises? Apologies for the confusion and I'd be glad to make this even clearer if you have a suggestion!

**Comment by timmyjose** [comment]
> I tried to add a clarification about the coordinate system earlier in commit [b88f788](https://github.com/moocfi/haskell-mooc/commit/b88f7882c91793f9a3f7c71d462b006319f8ad4d) – perhaps you're working on an older version of the exercises? Apologies for the confusion and I'd be glad to make this even clearer if you have a suggestion!

Thank you for clearing that up! I must admit that it's my mistake as I had not read that part at all. I should have read the comments in the exercises in order.  

Since the comment explains the coordinate system in use, I don't think there is really anything that should be changed (especially seeing as to no else has mentioned it), so I'll close the issue now. 

Thanks for the help, @muzimuzhi  and @opqdonut, and sorry for the unnecessary confusion! :-)

**Comment by timmyjose** [comment]
Closing since it is a non-issue. The comments in the file mentions how the coordinate system is supposed to work, and I failed to read it.
