### ISSUE TITLE
Set16a Ex6: Possible unintended way to pass tests

### ISSUE THREAD

**Issue by Preoo** [moocfi/haskell-mooc#35]
Should tests for ex6 accept a generator which always produces a list of repeating values?
For example list [1,1,1] satisfies all properties given in description, so 'solution' like this feels like sidestepping the problem:
```haskell
genList :: Gen [Int]
genList = do n <- choose (3,5)
             e <- elements [0..10]
             return (replicate n e)
```
If not then something like this could be reasonable unlikely to raise false positives:
```haskell
ex6_2 = once $ testGenMany genList 30 $ \ls ->
  conjoin [counterexample "  should have lists of all lengths" $ nub (sort (map length ls)) ?== [3,4,5]
          ,counterexample "  should at least 7 different ints" $ length (nub (sort (concat ls))) >= 7
          ,counterexample "  should not have only single repeating int" $ any ((> 1) . length . nub) ls]
```
so above example fails with:
> *** Failed! Falsified (after 1 test):
> Generated values: [[8,8,8,8,8],[4,4,4,4,4],[8,8,8,8,8],[8,8,8],[4,4,4,4,4],[4,4,4,4],[6,6,6],[1,1,1,1,1],[6,6,6],[2,2,2,2,2],[5,5,5,5],[3,3,3],[7,7,7],[4,4,4,4,4],[5,5,5,5],[1,1,1],[0,0,0,0],[6,6,6,6],[1,1,1,1,1],[10,10,10],[2,2,2],[7,7,7,7],[0,0,0],[6,6,6],[9,9,9,9,9],[6,6,6,6,6],[9,9,9,9,9],[0,0,0,0,0],[5,5,5],[4,4,4,4,4]]
>   should not have only single repeating int

**Comment by opqdonut** [comment]
good catch! thanks!
