### ISSUE TITLE
HLint to CI/CD

### ISSUE THREAD

**Issue by akirataguchi115** [moocfi/haskell-mooc#45]
Adding [HLint](https://github.com/ndmitchell/hlint) or some other lint to CI/CD would make the .hs files already linted and the user shouldn't have to lint and guess the style themselves.

**Comment by opqdonut** [comment]
I checked the hlint warnings for the SetX.hs files, and I didn't see anything I'd like to change. Would you like it if I added a `.hlint.yaml` file that disables all the checks I don't agree with? Then the exercise files would be hlint-clean, and hlint tips might help students.

**Comment by akirataguchi115** [comment]
Yes! a `.hlint.yaml` would defo help us see what's your perspective on good Haskell formatting 😸

**Comment by akirataguchi115** [comment]
I still think the `.hlint.yaml` would be a good addition to the repository :slightly_smiling_face:

**Comment by opqdonut** [comment]
I agree, I just haven't had the time/energy to look into it yet.

**Comment by opqdonut** [comment]
I looked through the hlint suggestions and they were mostly something that would confuse the students (e.g. change `foo x y = bar (f x) y` to `foo x = bar (f x)`, change `case x of Just y -> ...; Nothing -> ...` to `fromMaybe x ...`). I ended up adding a .hlint.yaml that disables all suggestions and enables just a few chosen ones. I hope this will make things a bit less confusing for beginners.
