### ISSUE TITLE
Incomplete graphic in 10.4.2 A Word About Sharing

### ISSUE THREAD

**Issue by jicksaw** [moocfi/haskell-mooc#49]
Looks like the expression tree SVG was cut off in https://github.com/moocfi/haskell-mooc/commit/8d839d9c459ce157ef584724d19a023964b99e27.

This is how Firefox is rendering it for me.

![image](https://user-images.githubusercontent.com/4146763/168494560-bb9c1c59-e11e-4539-9a24-11c774594700.png)

**Comment by opqdonut** [comment]
woops, thanks for noticing that!
