### ISSUE TITLE
Set9a Ex5 misspelling of "successful"

### ISSUE THREAD

**Issue by voneiden** [moocfi/haskell-mooc#54]
Minor one: Set9a Ex5 has three instances of "successful" misspelled as "succesful"

https://github.com/moocfi/haskell-mooc/blob/9269b95d9a230786badc4ef707509387a027ef77/exercises/Set9a.hs#L74
https://github.com/moocfi/haskell-mooc/blob/9269b95d9a230786badc4ef707509387a027ef77/exercises/Set9a.hs#L76
https://github.com/moocfi/haskell-mooc/blob/9269b95d9a230786badc4ef707509387a027ef77/exercises/Set9a.hs#L77

**Comment by voneiden** [comment]
https://github.com/moocfi/haskell-mooc/blob/master/exercises/Set13a.hs#L31 found a new variant

**Comment by opqdonut** [comment]
thanks, fixed!
