### ISSUE TITLE
Stack build fails

### ISSUE THREAD

**Issue by andrewbernard** [moocfi/haskell-mooc#64]
Ubuntu 22.04.1 LTS. Components used:

stack: 2.9.1
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

Stack build fails as follows:

$ stack build
Writing implicit global project config file to: /home/acb/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Using latest snapshot resolver: lts-19.25
Preparing to install GHC (tinfo6) to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-tinfo6-9.0.2.
Unpacking GHC into /home/acb/.stack/programs/x86_64-linux/ghc-tinfo6-9.0.2.temp/                                                                                gcc: error: unrecognized command-line option '--target=x86_64-unknown-linux'
Installed GHC.
Error parsing targets: The specified targets matched no packages.
Perhaps you need to run 'stack init'?

Unable to do the Exercises.

**Comment by opqdonut** [comment]
Did you run `stack build` inside the `exercises/` subdirectory of the repository?

**Comment by andrewbernard** [comment]
Ah! It would help if I actually read the perfectly clear instruction to build in the exercises directory. All works fine, of course.

**Comment by andrewbernard** [comment]
Ah! It would help if I actually read the perfectly clear instruction to build in the exercises directory. All works fine, of course.
