### ISSUE TITLE
Data.Traversable forbidden on haskell.mooc.fi yet not forbidden in haskell-mooc/exercises/Set11aTest.hs

### ISSUE THREAD

**Issue by JuhaJGamer** [moocfi/haskell-mooc#76]
**Description**: See title 
**Expected behaviour**: Server and git repository agree on the legality of imports
**Actual behaviour**: Server disallows forM/mapM/Data.Traversable, while Set11aTest.hs in the repository allows it.
**Replication**:   
    1. Attempt to use forM or mapM in Set11a.hs
    2. Run `stack runhaskell Set11aTest.hs`, noting the fact it passes without issue. 
    3. Try to submit it on haskell.mooc.fi
    4. Disintegrate as your tests fail
 
Related text wall:
![image](https://user-images.githubusercontent.com/20599733/212468275-72a291ff-f04f-425b-8bc2-104695524f15.png)

**Comment by opqdonut** [comment]
That's weird. I'll check that the tests on the server are up to date.

**Comment by opqdonut** [comment]
Fixed, thanks for reporting!
