### ISSUE TITLE
Rendering problem on iPadOS

### ISSUE THREAD

**Issue by wolverian** [moocfi/haskell-mooc#8]
Browser: Safari on iPadOS 14.0

Expected: text in code blocks is visible

What actually happens: text in code blocks is initially invisible. Switching to another browser tab and back makes the currently on-screen code blocks visible, but not any code blocks outside the current viewport.

Demonstration:
 
![EA54DB80-89F2-4CA6-8B3D-3D95FE6C73DE](https://user-images.githubusercontent.com/42124/93855269-e807cd80-fcbf-11ea-977d-012b3a9cc5ed.png)

**Comment by wolverian** [comment]
This might very well be a browser bug, but I thought it’s worth mentioning here.

**Comment by opqdonut** [comment]
thanks for the report, but I have no idea how to fix it :scream:

**Comment by wolverian** [comment]
I have no idea either. 🙂  If you want to debug the issue, you’ll need an iPad to test with, connect it to a MacBook and open Safari’s Developer tools. It might be good to also check if this happens on iPadOS 13.

**Comment by wolverian** [comment]
Nice! 👍
