### ISSUE TITLE
Ex 6 of Set4a.hs

### ISSUE THREAD

**Issue by 09-code** [moocfi/haskell-mooc#88]
```hs
-- Examples:
--   incrementKey True [(True,1),(False,3),(True,4)] ==> [(True,2),(False,3),(True,5)]
```

I think `[(True,2),(True,5)]` is correct.

**Comment by muzimuzhi** [comment]
Usually the description of a coding exercise is not as formal and comprehensive as possible, hence the provided examples may be used as additions to what's missing in the description. So learners are usually expected to follow what can be inferred from example inputs and outputs, not to argue with.
