### ISSUE TITLE
2.3.1 List Operations: missing `last`

### ISSUE THREAD

**Issue by eNV25** [moocfi/haskell-mooc#93]
```
init :: [a] -> [a]          -- returns everything except the last element
```

`init` is mentioned but not `last`.

**Comment by opqdonut** [comment]
Thanks for noticing that!

**Comment by muzimuzhi** [comment]
The doc for `last` introduced in https://github.com/moocfi/haskell-mooc/commit/c196d01e8689f052f01f65a3663b092be3b69ac8 is wrong. Currently it reads "returns everything except the last element" but it should be "returns the last element".

**Comment by opqdonut** [comment]
oof, shouldn't edit the text so late at night
