### ISSUE TITLE
Use HTTPS for external links when possible (round 2)

### ISSUE THREAD

**Issue by muzimuzhi** [moocfi/haskell-mooc#95]
Similar to my previous issue #26 created and resolved almost three years ago, this issue mainly focus on Part 2 and the site for book _Real World Haskell_.

To be updated to HTTPS (filtered by `grep -rn --exclude-dir=img 'http:' .`)
- several http://book.realworldhaskell.org in both `part1.html` and `part2.html`
- https://httpbin.org/base64/aGFza2VsbCBmb3IgZXZlcgo= in `part2.html` and `exercises/Examples/FetchWords.hs`
- three occurrences of http://hackage.haskell.org/package/warp-3.3.14 in `part2.html`
- http://oleg.fi/gists/posts/2017-04-18-glassery.html in `part2.html`
- three occurrences of http://creativecommonse.org/licenses/by-sa/4.0/ in `LICENSE` and `README.md`

I didn't take the Part 2, hence don't know if localhost URLs in `part2.html` and its exercises support HTTPS or not.

Remaining HTTP-only site
- http://learnyouahaskell.com

**Comment by opqdonut** [comment]
Thanks! Will be fixed soon.

**Comment by opqdonut** [comment]
Thanks for your attention to detail!
