### ISSUE TITLE
Set 7 Ex 8 Passes locally, but not on the website

### ISSUE THREAD

**Issue by i-hate-nicknames** [moocfi/haskell-mooc#96]
I'm getting the following error on the website:

```
*** Failed! Falsified (after 1 test):
The type of 'Multiply1'
  Expected: Int -> Int -> Operation1
  Was: MulArrowT PromotedT GHC.Types.One Int MulArrowT PromotedT GHC.Types.One Int Operation1
```

I'm checking the type in ghci and it seems to be what is expected:

```
ghci> :t Multiply1
Multiply1 :: Int -> Int -> Operation1
```

I'm using `ghc-9` branch

**Comment by opqdonut** [comment]
Could you try again? We just upgraded the course server to use GHC 9 and there were some left over problems, but they should be fixed now.

**Comment by i-hate-nicknames** [comment]
Yes, works now. Many thanks for the awesome course!
